#!/usr/bin/env bash

curl "http://apache.dataphone.se/lucene/solr/1.4.0/apache-solr-1.4.0.zip" > apache-solr-1.4.0.zip.zip
unzip apache-solr-1.4.0.zip

rm apache-solr-1.4.0.zip
rm -fr solr

mv apache-solr-nightly/example solr
rm -fr apache-solr-nightly

cp drupal-config/* solr/solr/conf/